---
vars:
  region: "%{hiera('region')}"
  state_bucket_name: "%{hiera('deployment_statebucket_name')}"
  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

backend_config:
  region: "%{hiera('region')}"
  bucket: "%{hiera('delivery_statebucket_name')}"
  key: "deployment-%{hiera('deployment_identifier')}/statebucket.tfstate"
  encrypt: "%{hiera('delivery_statebucket_is_encrypted')}"
