---
vars:
  region: "%{hiera('region')}"
  state_bucket_name: "%{hiera('deployment_statebucket_name')}"
  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"
