---
vars:
  region: "%{hiera('region')}"
  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  domain_name: "%{hiera('domain_name')}"
  private_domain_name: "%{hiera('private_domain_name')}"
  private_network_cidr: "%{hiera('private_network_cidr')}"

  # The Rakefile needs to set this same path.
  # I would prefer to have the Rakefile directly inject this, to avoid dependency on
  # remembering to put the same path in multiple locations.
  cluster_instance_ssh_public_key_path: "../ssh_keys/cluster_instance_ssh_key.pub"
  cluster_instance_type: "t2.medium"

ssh_keys:
  - cluster_instance_ssh_key

