---
vars:
  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"
  domain_name: "%{hiera('domain_name')}"
  private_domain_name: "%{hiera('private_domain_name')}"
  private_network_cidr: "%{hiera('private_network_cidr')}"

  region: "%{hiera('region')}"
  state_bucket_name: "%{hiera('estate')}-delivery-%{hiera('component')}"
  
  cluster_instance_ssh_public_key_path: "%{hiera('cluster_instance_ssh_public_key_path')}"
  cluster_instance_type: "t2.medium"
